
CREATE TABLE USERS(
    ID BIGSERIAL PRIMARY KEY,
    USER_NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    PHONE_NUMBER TEXT DEFAULT 'Aucun numero',
    PASSWORD TEXT DEFAULT 'No password',
    CREATED_AT TIMESTAMP,
    PROFILE_PICTURE_URL TEXT DEFAULT 'https://cdn2.iconfinder.com/data/icons/ios-7-icons/50/user_male2-512.png',
    LOCATION TEXT DEFAULT 'Abidjan',
    PIN CHAR(5) DEFAULT 'NULL'
);

CREATE TABLE ADVERTS (
    ID BIGSERIAL PRIMARY KEY,
    LOCATION TEXT NOT NULL, 
    OWNER_ID INTEGER REFERENCES USERS (ID),
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT DEFAULT 'Aucune description',
    CATEGORY TEXT NOT NULL,
    PRICE BIGINT DEFAULT 0,
    CONTACT TEXT,
    AD_UID TEXT NOT NULL,
    ADDRESS TEXT,
    CREATED_AT TIMESTAMP
);

CREATE TABLE IMAGES_URL (
    ADVERT_ID INTEGER REFERENCES ADVERTS (ID),
    URL TEXT NOT NULL
);

CREATE TABLE MESSAGES (
    ID SERIAL PRIMARY KEY,
    SENDER_ID INTEGER REFERENCES USERS (ID),
    RECEIVER_ID INTEGER REFERENCES USERS (ID),
    BODY TEXT NOT NULL
);

CREATE TABLE RATINGS (
    ID SERIAL PRIMARY KEY,
    SENDER_ID INTEGER REFERENCES USERS (ID),
    RECEIVER_ID INTEGER REFERENCES USERS (ID),
    VALUE INTEGER CHECK (VALUE <= 5)
);

CREATE TABLE FAVORITES (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID INTEGER REFERENCES USERS (ID),
    ADVERT_ID INTEGER REFERENCES ADVERTS (ID)
);
